'use client'
// export const metadata = {
//     title: 'Products',
//     description: 'Generated by hitesh',
// }

  
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    const random = Math.floor(Math.random()* 2);
    
    if(random ===1){
      throw Error("Products Error review --- ")
    }

    return (
        <>
        <div className="md:container md:mx-auto">
        {children}
        <h2>Products Layout</h2>
        </div>
        </>  
    )
  }
  