import Navbar from "../components/navbar";
import "./style.css";

export const metadata = {
    title: 'Dashboard',
    description: 'Generated by hitesh',
  }

  
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
        <div className="md:container md:mx-auto">
        <Navbar />
        {children}
        </div>
        </>  
    )
  }
  